### ISSUE TITLE
anyway to automatically run changes?

### ISSUE THREAD

**Issue by lobbyforge** [mykhael/websheet#1]
I'm currently just restarting the server by the `node index.js` command every change but is there anyway to actually submit code and the changes just load/refresh?

**Comment by mykhael** [comment]
@lobbyforge this is already implemented via the `npm start` command which uses [nodemon](https://www.npmjs.com/package/nodemon) currently, but I really need to implement documentation to this repository though :)

**Comment by lobbyforge** [comment]
@mykhael ohhhhhhhhhh man thanks I should have known :+1:
